config/routes.rb
Rbus::Application.routes.draw do

  resources :intended_trips do 
    collection do
      get 'my'
    end
  end
  resources :bus_stops

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  match '/feedback' => 'home#feedback', :via => :post
  match '/demo'     => 'home#demo', :via => :get

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      redirect_to my_intended_trips_path
    else
      @intended_trip = IntendedTrip.new
    end
  end

  # posts feedback to svs@svs.io
  def feedback
    FeedbackMailer.feedback(params[:email], params[:body]).deliver
    redirect_to root_path, {success: "Thanks for the feedback. We'll be in touch shortly."}
  end

  def demo
    render
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
:plain
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=73675367324";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


.row{:style => "margin-bottom: 0px"}
  .span4#headline
    %h1 Mumbai,
    %h2
      Stress free commutes are here
      %span.highlight
        from Rs.1800 only!
    %h3
      Simply leave us your commute details and we'll arrange for you a
      %span.highlight point-to-point
      bus with
      %span.highlight guaranteed seating
      ,
      %span.highlight flexible timings
      &amp;
      %span.highlight your level of luxury.
    %div{:style => "padding: 5px; margin-top: 15px"}
      As seen in
      %br
      %a{:href => "http://www.pluggd.in/rbus-attempts-to-reduce-traffic-in-mumbai-by-creating-buspools-297/", :target => "_blank"}
        = image_tag 'pi.jpeg'
      %a{:href => "http://www.dnaindia.com/mumbai/report_bus-pool-may-take-you-to-work-soon_1734424", :target => "_blank"}
        = image_tag 'logo-dna.gif'

  .span5{:style => "display: table"}
    .row{:style => "margin: auto"}
      %h1
        = link_to "#{IntendedTrip.count} commutes registered", intended_trips_path

      #new_form{:style => "display: table-cell; vertical-align: middle;"}
        = render 'intended_trips/form'

  .span3
    <div style="margin-top: 1.5em;">&nbsp;</div>
    :plain
      <a class="twitter-timeline" href="https://twitter.com/rbus_in" data-widget-id="376572078842863616">Tweets by @rbus_in</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out rBus.in - stress free commutes for Mumbai" data-via="rbus_in" data-size="large">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>



.row{:style => "position: relative; top: 50px; margin-bottom: 50px;"}
  %ul.thumbnails
    %li.span4
      = image_tag 'gps.png'
      %h1
        Zero Waiting
      Wait for your bus in the comfort of your home or office, and be alerted as it approaches
    %li.span4
      = image_tag 'qrcode.png'
      %h1
        Guaranteed Seat
      Book your seat in advance and ride daily in comfort with no tension.
    %li.span4
      = image_tag 'bus-icon.png', :style => "padding-bottom: 40px"
      %h1
        Flexible timings
      Running early or late? No problem. Reserve a seat on a different bus and travel at your convenience.

.row#pricing
  %h1 plans and pricing
  Commuter plans start from monthly payment of
  %span.highlight
    Rs. 1800 for trips less than 20km (round trip)
  going up to
  %span.highlight
    Rs. 4000 for 80 km (round trip)
  commute for
  %span.highlight
    non a/c bus.
  For a/c, the rates are
  %span.highlight
    Rs. 2800
  and
  %span.highlight
    Rs. 7000
  respectively.
  %span.highlight
    More people sign up, cheaper it gets!


  %p
    %h2 See how our pricing compares with other modes of transport
    %table.table#pricing
      %thead
        %tr
          %th mode of commute
          %th monthly cost
          %th comfort
          %th safety
      %tr
        %th BEST
        %td 600
        %td
          - 2.times do |i|
            = image_tag('saddey.png')

        %td
          - 2.times do |i|
            = image_tag('smiley.png')

      %tr
        %th train + rickshaw
        %td 1000
        %td
          - 2.times do |i|
            = image_tag('saddey.png')
        %td
          - 1.times do |i|
            = image_tag('saddey.png')
      %tr
        %th motorcycle
        %td 1500
        %td
          - 3.times do |i|
            = image_tag('saddey.png')
        %td
          - 3.times do |i|
            = image_tag('saddey.png')
      %tr.yellow-gradient
        %th rBus non-a/c
        %td 2000
        %td
          - 2.times do |i|
            = image_tag('smiley.png')
        %td
          - 3.times do |i|
            = image_tag('smiley.png')

      %tr.yellow-gradient
        %th rBus a/c
        %td 3000
        %td
          - 3.times do |i|
            = image_tag('smiley.png')
        %td
          - 3.times do |i|
            = image_tag('smiley.png')

      %tr
        %th rickshaw
        %td 3000
        %td
          - 2.times do |i|
            = image_tag('saddey.png')

        %td
          - 1.times do |i|
            = image_tag('saddey.png')

      %tr
        %th self driven car
        %td 12000
        %td
          - 2.times do |i|
            = image_tag('smiley.png')
        %td
          - 3.times do |i|
            = image_tag('smiley.png')

      %tr
        %th chauffeur-driven car
        %td 20000
        %td
          - 3.times do |i|
            = image_tag('smiley.png')
        %td
          - 2.times do |i|
            = image_tag('smiley.png')


.row
  %h1 frequently asked questions
  #faq
    %h3 How does it work, exactly?
    rBus works very simply. First, we gather the commute details of people. Then, when we find enough of them going from the same place to the same place, we
    start running buses between those points. If we find say 200 people, it means we can run 10 twenty-seater buses on that route, which gives you ample
    flexibility in terms of timings. We wire up the buses with GPS and voila - your personal public transport system!
    %h3 Can we have rBus in my city?
    rBus is Open Source.
    %a{:href => "http://github.com/svs/rbus"} Go for it!
    Please! Someone fix Mumbai traffic!! And btw, you'll have to find a different name for it.