config/routes.rb
Rbus::Application.routes.draw do

  resources :intended_trips do 
    collection do
      get 'my'
    end
  end
  resources :bus_stops

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  match '/feedback' => 'home#feedback', :via => :post
  match '/demo'     => 'home#demo', :via => :get

  root :to => 'home#index'

end

app/models/intended_trip.rb
class IntendedTrip
  include DataMapper::Resource
  property :id, Serial

  property :on, Enum["weekdays", "weekdays and saturday", "all days"], :required => true

  property :from_name, String, :required => true, :length => 150;
  property :from_lat, Decimal, :precision => 18, :scale => 15, :required => true, :max => 90, :min => -90
  property :from_lng, Decimal, :precision => 18, :scale => 15, :required => true, :max => 90, :min => -90

  property :to_name, String, :required => true, :length => 150;
  property :to_lat, Decimal, :precision => 18, :scale => 15, :required => true, :max => 90, :min => -90
  property :to_lng, Decimal, :precision => 18, :scale => 15, :required => true, :max => 90, :min => -90

  property :type, String

  belongs_to :user

  property :created_at, DateTime
  property :updated_at, DateTime
  property :deleted_at, ParanoidDateTime


  # accepts_nested_attributes_for :user

  # Public: finds all the trips starting and ending within a particular radius of this trip
  # meters -> the radius within which to search. currently returns trips where the sum of the start distance and end distance is less than this parameter
  def trips_within(meters)
    f = distance(:from)
    t = distance(:to)
    trips_with_distance.where{(f + t <= meters)}.exclude(:id => self.id).all
  end

  # Public: gets the nearest trips, sorted by a given order
  # params     ->  a Hash with keys for limit and offset. Defaults to {:limit => 20, :offset => 0}
  # sort_order -> one of :from, :to or :total, specifying whether to sort on distance at start, distance at end or total distance. Defaults to :total
  def nearest_trips(params = {}, sort_order = :total)
    params = {:limit => 100, :offset => 0}.merge(params)
    sorted_trips = trips_with_distance.order(distance(:from) + distance(:to))
    sorted_trips.map{|t| {
        :trip => IntendedTrip.get(t[:id]),
        :start_distance => t[:fdist],
        :end_distance => t[:tdist],
        :total_distance => t[:fdist] + t[:tdist]
      } unless t[:id] == self.id}.compact.select{|x| x[:trip]}
  end


  # Public: return trips that match the given lat/lng filters
  # options  -> a Hash with the following keys
  #     from ->  a Hash with keys lat1, lng1, lat2, lng2 representing the coordinates within which the trip must start
  #     to   ->  a Hash with keys lat1, lng1, lat2, lng2 representing the coordinates within which the trip must start
  # returns a DataMapper::Collection of IntendedTrips
  # example: Trip.filter(:from => {:lat1 => 19, :lng1 => 72, :lat2 => 20, :lng2 => 73})
  def self.filter(options = nil)
    return self.all unless options
    q = {}
    if f = options[:from]
      q[:from_lat.gte] = f[:lat1]
      q[:from_lng.gte] = f[:lng1]
      q[:from_lat.lte] = f[:lat2]
      q[:from_lng.lte] = f[:lng2]
    end
    if t = options[:to]
      q[:to_lat.gte] = t[:lat1]
      q[:to_lng.gte] = t[:lng1]
      q[:to_lat.lte] = t[:lat2]
      q[:to_lng.lte] = t[:lng2]
    end
    self.all(q)
  end

  def inspect
    "[#{id}: from #{from_name}(#{from_lat},#{from_lng}) to #{to_name}(#{to_lat},#{to_lng}) on #{on}]"
  end

  # Returns similiar trips to the trip being passed. We only select those trips whose start, end points are within kilometre of the
  # start and end points of the trip being passed.
  def similiar_trips( new_trip )
    similiar_trips = DB[ :intended_trips ].
        select(
                Sequel.as( new_trip[ :id ], "trip_id" ),
                Sequel.as( :id, "other_trip_id" ),
                Sequel.as( Sequel.lit( "(? <@> ?)*1609", Sequel.function( :POINT, new_trip[ :from_lng ], new_trip[ :from_lat ]), Sequel.function( :POINT, :from_lng, :from_lat ) ), "start_dist" ),
                Sequel.as( Sequel.lit( "(? <@> ?)*1609", Sequel.function( :POINT, new_trip[ :to_lng ], new_trip[ :to_lat ]), Sequel.function( :POINT, :to_lng, :to_lat ) ), "to_dist" )
        ).
        where("earth_box( ll_to_earth( #{new_trip[ :from_lat ]}, #{new_trip[ :from_lng ]} ), 1000 ) @> ll_to_earth( from_lat, from_lng ) and earth_box( ll_to_earth(#{new_trip[ :to_lat ]}, #{new_trip[ :to_lng ]}), 1000  ) @> ll_to_earth( to_lat, to_lng )").exclude( :id => new_trip[ :id ])

  DB[ :similiar_trips ].where( :trip_id => new_trip[ :id ] ).delete
  DB[ :similiar_trips ].import( [ :trip_id, :other_trip_id, :start_distance, :end_distance] , similiar_trips)
    
  end

  private

  # Returns all the other trips in the database with their fdist and tdist calculated
  def trips_with_distance
    DB[:intended_trips].select(:id, :from_name, :to_name,
                               :from_lat, :from_lng,
                               :to_lat, :to_lng,
                               distance(:from).as(:fdist),
                               distance(:to).as(:tdist)
                               ).where(:deleted_at => nil)
  end

  # Returns a Sequel.function to calculate the distance between a trip and all other trips
  def distance(what)
    lat, lng = "#{what}_lat".to_sym, "#{what}_lng".to_sym
    Sequel.function(:earth_distance,
                    Sequel.function(:ll_to_earth, self.send(lat), self.send(lng)),
                    Sequel.function(:ll_to_earth, lat, lng)
                    )
  end


end

app/controllers/intended_trips_controller.rb
class IntendedTripsController < ApplicationController
  # GET /intended_trips
  # GET /intended_trips.json

  load_and_authorize_resource

  def index
    @intended_trips = IntendedTrip.filter(params)
    respond_to do |format|
      format.html {
        (render :map and return) if params[:map]
        (render :filter and return) if (params[:from] || params[:to] || params[:filter])
        render
      }
      format.json { render json: @intended_trips}
    end
  end

  def my
    unless current_user
      redirect_to new_user_session_path  and return
    end
    @intended_trips = IntendedTrip.all(:user => current_user)
    respond_to do |format|
      format.html { render 'index'}
      format.json { render json: @intended_trips }
    end
  end

  # GET /intended_trips/1
  # GET /intended_trips/1.json
  def show
    @intended_trip = IntendedTrip.get(params[:id])
    @intended_trips = @intended_trip.trips_within(2000)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @intended_trip }
    end
  end

  # GET /intended_trips/new
  # GET /intended_trips/new.json
  def new
    @intended_trip = IntendedTrip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @intended_trip }
    end
  end

  # GET /intended_trips/1/edit
  def edit
    @intended_trip = IntendedTrip.get(params[:id])
    raise unless @intended_trip.user == current_user
  end

  # POST /intended_trips
  # POST /intended_trips.json
  def create
    if !current_user
      @user = User.first(:email => params[:intended_trip][:user][:email]) if params[:intended_trip][:user] # and this email address does not exist in our database
      if @user
        redirect_to new_user_session_path, {alert: "Please give us your password"} and return
      end
      @new_user = true
    else
      params[:intended_trip][:user_id] ||= current_user.id
    end
    @intended_trip_creator = IntendedTripCreator.new(params[:intended_trip])
    @intended_trip = @intended_trip_creator.trip
    if (current_ability.can?(:manage, @intended_trip_creator.trip)) || !current_user
      respond_to do |format|
        new_trip = @intended_trip_creator.save
        if new_trip          
          AdminMailer.notify(@intended_trip_creator.trip).deliver
          @intended_trip.similiar_trips( new_trip )
          msg =  'Thanks for registering your commute'
          msg += "We've just sent you and email. Kindly confirm your email address by clicking on the confirm link in it." if @new_user
          format.html { redirect_to @intended_trip_creator.trip, notice: msg }
          format.json { render json: @intended_trip_creator.trip, status: :created, location: @intended_trip }
        else
          if !(@intended_trip_creator.trip.errors.keys && [:from_stop_id, :to_stop_id]).empty?
            @map = true
          end
          format.html { render action: "new" }
          format.json { render json: @intended_trip.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to intended_trips_path, error: "You do not have sufficient privileges to do this"
    end
  end

  # PUT /intended_trips/1
  # PUT /intended_trips/1.json
  def update
    @intended_trip = IntendedTrip.get(params[:id])
    @intended_trip.similiar_trips( @intended_trip )
    respond_to do |format|
      if @intended_trip.save
        format.html { redirect_to @intended_trip, notice: 'Your trip has been updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @intended_trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intended_trips/1
  # DELETE /intended_trips/1.json
  def destroy
    @intended_trip = IntendedTrip.get(params[:id])
    raise unless @intended_trip.user == current_user
    @intended_trip.destroy

    respond_to do |format|
      format.html { redirect_to intended_trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/intended_trips_helper.rb
module IntendedTripsHelper
end

app/views/intended_trips/_form.html.haml
%script{:type => "text/javascript" , :src => "http://maps.googleapis.com/maps/api/js?key=#{Yetting.maps}&sensor=false"}
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
= javascript_include_tag 'map_functions'
= javascript_include_tag 'ui.geo_autocomplete'
:javascript
  $(document).ready(function() {
    x = 0; y = 0;
    $('#from').keypress(function(e) {
      if ((e.which > 0) && (e.which != 13) ){
        $('#intended_trip_from_lat').attr('value','')
        $('#intended_trip_from_lng').attr('value','')
      }
    });
    $('#to').keypress(function(e) {
      if ((e.which > 0) && (e.which != 13) ){
        $('#intended_trip_to_lat').attr('value','')
        $('#intended_trip_to_lng').attr('value','')
      }
    });

    if ($('#map').length == 1) {
      map = new google.maps.Map(document.getElementById("map"), { mapTypeId: google.maps.MapTypeId.ROADMAP, center: new google.maps.LatLng(19.09, 72.91), zoom: 11 });
      infowindow = new google.maps.InfoWindow();
      marker = new google.maps.Marker({
        map: map
      });
    }
    var defaultBounds = new google.maps.LatLngBounds(
    new google.maps.LatLng(18, 71),
    new google.maps.LatLng(19, 73));

    var from_input = document.getElementById('from');
    var to_input = document.getElementById('to');
    var options = {
      bounds: defaultBounds,
      types: ['establishment','geocode'],
      componentRestrictions: {country: 'in'}
    };

    from_autocomplete = new google.maps.places.Autocomplete(from_input, options);
    to_autocomplete = new google.maps.places.Autocomplete(to_input, options);


    google.maps.event.addListener(from_autocomplete, 'place_changed', function() {place_changed("from");});
    google.maps.event.addListener(to_autocomplete, 'place_changed', function() {place_changed("to");});

  });


  function place_changed(which) {
    autocomplete = which == "from" ? from_autocomplete : to_autocomplete
    var place = autocomplete.getPlace();
    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }
    if ((typeof infowindow != "undefined")) {
      infowindow.close();
      infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
      infowindow.open(map, marker);
    }
    if ((typeof map != "undefined")) {
      if (place.geometry.viewport) {
        map.fitBounds(place.geometry.viewport);
      } else {
        map.setCenter(place.geometry.location);
        map.setZoom(17);  // Why 17? Because it looks good.
        var image = new google.maps.MarkerImage(
          place.icon,
          new google.maps.Size(71, 71),
          new google.maps.Point(0, 0),
          new google.maps.Point(17, 34),
          new google.maps.Size(35, 35)
        );
        marker.setIcon(image);
        marker.setPosition(place.geometry.location);
      }

    }

    $('#intended_trip_' + which + '_name').attr('value', $('#' + which).attr('value').split(",")[0]);
    $('#intended_trip_' + which + '_lat').attr('value', place.geometry.location.lat());
    $('#intended_trip_' + which + '_lng').attr('value', place.geometry.location.lng());
  }

#change
#kp
%div#form
  -if @intended_trip.errors.any? || (@intended_trip.user && @intended_trip.user.errors.any?)
    #error_explanation
      %h2= "#{pluralize(@intended_trip.errors.count + @intended_trip.user.errors.count, "error")} prohibited this intended_trip from being saved:"
      %ul
        - (@intended_trip.errors.full_messages + @intended_trip.user.errors.full_messages).each do |msg|
          %li= msg
  %form{:style => "margin: 0px;"}
    %label I live at
    %input{:id => "from", :value => @intended_trip.from_name}
    %br
    %label and work at
    %input{:id => "to", :value => @intended_trip.to_name}
  = form_for @intended_trip do |f|
    = f.hidden_field :from_name, :class => "span4", :placeholder => "i.e. Inorbit Mall", :value => params[:from] || @intended_trip.from_name
    = f.hidden_field :from_lat
    = f.hidden_field :from_lng
    = f.hidden_field :to_name, :class => "span4", :placeholder => "i.e. Marol", :value => params[:to] || @intended_trip.to_name
    = f.hidden_field :to_lat
    = f.hidden_field :to_lng
    %label on
    = f.select :on, ["weekdays", "weekdays and saturday", "all days"]
    %label type
    = f.select :type, ["a/c", "non-a/c"]
    %br
    - unless current_user
      = f.fields_for :user do |u|
        %label Email
        = u.text_field :email, :value => (params[:intended_trip][:user][:email] rescue nil)
        %br
        %label Password
        = u.text_field :password, :placeholder => "please choose a password", :type => "password", :value => (params[:intended_trip][:user][:password] rescue nil)
        %br
        %label Confirm Password
        = u.text_field :password_confirmation, :placeholder => "please type your password again", :type => "password", :value => (params[:intended_trip][:user][:password_confirmation] rescue nil)
        %br
    = f.submit "Register my Trip", :class => "btn btn-info"

app/views/intended_trips/_list.html.haml
- if @intended_trips.count > 0

  %table.table
    %thead
      %tr
        %th
          From
        %th
          To
        %th
          On
        %th Nearby Trips
        %th{:colspan => "3"}
          Actions
    - @intended_trips.each do |intended_trip|
      %tr
        %td
          = intended_trip.from_name
        %td
          = intended_trip.to_name
        %td
          = intended_trip.on
        %td
          = intended_trip.trip_stats.trips_within_2_km
        - if intended_trip.user == current_user
          %td= link_to 'Show', intended_trip
          %td= link_to 'Edit', edit_intended_trip_path(intended_trip)
          %td= link_to 'Destroy', intended_trip, :data => {:confirm => 'Are you sure?'}, :method => :delete

app/views/intended_trips/_nearest_list.html.haml
:plain
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=73675367324";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

%div
  %h2
    %span.highlight.bigger
      = @intended_trips.count
    trips within 2 kms
  %h3 
    Spread the word!
    %br
    %a{:href => "https://twitter.com/share", :class => "twitter-share-button", :'data-text' => "Come join my commute from #{@intended_trip.from_name} to #{@intended_trip.to_name}", :'data-via' => "rbus_in", :'data-size' => "large"} Tweet
    <div class="fb-like" data-href=#{request.path} data-send="true" data-width="450" data-show-faces="true"></div>

- if @intended_trips.count > 0
  %table.table
    %thead
      %tr
        %th
          From
        %th
          To
    - @intended_trips.each do |intended_trip|
      %tr
        %td
          = intended_trip[:from_name]
          = "(#{(intended_trip[:fdist]/1000).round(2)} kms away)" rescue ""
        %td
          = intended_trip[:to_name]
          = "(#{(intended_trip[:tdist]/1000).round(2)} kms away)" rescue ""

  
  
  

app/views/intended_trips/edit.html.haml
%h1 Editing intended_trip

= render 'form'

= link_to 'Show', @intended_trip
\|
= link_to 'Back', intended_trips_path

app/views/intended_trips/filter.html.haml
%script{:type => "text/javascript" , :src => "http://maps.googleapis.com/maps/api/js?key=#{Yetting.maps}&sensor=false"}
= javascript_include_tag 'map_functions'

:javascript
  var map1_loaded = false, map2_loaded = false;
  function map_loaded(which) {
    if (which == 1) {
      map1_loaded = true;
    }
    if (which == 2) {
      map2_loaded = true;
    }
    if (map1_loaded && map2_loaded) {
      loadTrips(map1,map2);
      loadTrips(map1,map2);
    }
  }      
  
  $(document).ready(function() {
    map1 = new google.maps.Map(document.getElementById("map1"), { mapTypeId: google.maps.MapTypeId.ROADMAP, center: new google.maps.LatLng(19.09, 72.91), zoom: 11 });
    map2 = new google.maps.Map(document.getElementById("map2"), { mapTypeId: google.maps.MapTypeId.ROADMAP, center: new google.maps.LatLng(19.09, 72.91), zoom: 11 });
    google.maps.event.addListenerOnce(map1, 'idle', function(){
      map_loaded(1);
    });    
    google.maps.event.addListenerOnce(map2, 'idle', function(){
      map_loaded(2);
    });    

    google.maps.event.addListener(map1, 'dragend', function() {
      loadTrips(map1,map2);
    });
    google.maps.event.addListener(map1, 'zoomend', function() {
      loadTrips(map1,map2);
    });

    google.maps.event.addListener(map2, 'dragend', function() {
      loadTrips(map1,map2);
    });
    google.maps.event.addListener(map2, 'zoomend', function() {
      loadTrips(map1,map2);
    });
  });

%h1
  %span.tripcount
    = @intended_trips.count
  = pluralize(@intended_trips.count, "trip").split(" ")[-1] 
.row
  .span5
    #map1.map{:style => "width: 450px; height: 400px"}
  .span5
    #map2.map{:style => "width: 450px; height: 400px"}

app/views/intended_trips/index.html.haml
.row{:style => "vertical-align: bottom"}
  .span6
    #headline
      %h1
        %span.highlight.bigger
          = @intended_trips.count
        commutes registered
  .span2{:style => "vertical-align: middle"}
    %h1.btn.btn-success.button
      = link_to '+', new_intended_trip_path

= render 'intended_trips/list'

app/views/intended_trips/map.html.haml
%h1
  == #{@intended_trips.count} commutes registered

%h3= link_to 'See as list', intended_trips_path
%script{:type => "text/javascript" , :src => "http://maps.googleapis.com/maps/api/js?key=#{Yetting.maps}&sensor=false"}
:javascript
  function initialize() {
    var myOptions = {
      center: new google.maps.LatLng(19.1, 72.9),
      zoom: 11,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map"),
    myOptions);
  }

  function load_trips() {
    $.get('/intended_trips.json', function(data) {
      $.each(data, function() { 
        // draw the line
        lat1 = parseFloat(this.from_lat);
        lng1 = parseFloat(this.from_lng);
        lat2 = parseFloat(this.to_lat);
        lng2 = parseFloat(this.to_lng);
        p = new google.maps.Polyline( {
          path: [ new google.maps.LatLng(lat1,lng1), 
                  new google.maps.LatLng(lat2, lng2)],
          strokeColor: "#ff0000",
          strokeWeight: 1
        });
        p.setMap(map);
        new google.maps.Marker({
          map: map,
          position: new google.maps.LatLng(lat1, lng1),
          icon: '/images/mm_20_green.png'
        })
        new google.maps.Marker({
          map: map,
          position: new google.maps.LatLng(lat2, lng2),
          icon: '/images/mm_20_red.png'
        })

      });
    });
  }

  $(document).ready(function() { 
    initialize();
    load_trips();
  });

#map.map{:style => "width:800px; height: 500px"}

app/views/intended_trips/new.html.haml
%h1 Register a New Commute
%h3
  Having trouble registering? 
  %a{:href => "http://www.screenr.com/U9f8", :target => "_blank"}
    See this small video
  
.row
  .span6
    = render 'form'
  .span6
    #map{:style => "width: 100%; height: 500px;"}

app/views/intended_trips/show.html.haml
%script{:type => "text/javascript" , :src => "http://maps.googleapis.com/maps/api/js?key=#{Yetting.maps}&sensor=false"}
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>

:javascript
  $(document).ready(function() {
    if ($('#map').length == 1) {
      map = new google.maps.Map(document.getElementById("map"), { mapTypeId: google.maps.MapTypeId.ROADMAP, center: new google.maps.LatLng(19.09, 72.91), zoom: 11 });
      infowindow = new google.maps.InfoWindow();
      marker = new google.maps.Marker({
        map: map
      });
    }
  });

%div{:style => "line-height: 1.2em"}
  %h2
    %span.bigger.highlight
      = @intended_trip.from_name
    to
    %span.bigger.highlight
      = @intended_trip.to_name
  - if can?(:edit, @intended_trip)
    = link_to 'Edit', edit_intended_trip_path(@intended_trip), :class => "btn btn-info"

%br

.row
  .span6
    = render 'intended_trips/nearest_list'
  .span6
    %div#map{:style => "width: 100%; height: 500px"}