config/routes.rb
Rbus::Application.routes.draw do

  resources :intended_trips do 
    collection do
      get 'my'
    end
  end
  resources :bus_stops

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  match '/feedback' => 'home#feedback', :via => :post
  match '/demo'     => 'home#demo', :via => :get

  root :to => 'home#index'

end

app/controllers/bus_stops_controller.rb
class BusStopsController < ApplicationController
  # GET /bus_stops
  # GET /bus_stops.json

  load_and_authorize_resource

  def index
    if params[:term]
      @bus_stops = BusStop.all(:conditions => ["name ilike ?","%#{params[:term]}%"])
    elsif params[:x1] and params[:y1] and params[:x2] and params[:y1]
      @bus_stops = BusStop.all(:conditions => ["lat BETWEEN ? AND ? AND lng BETWEEN ? AND ?",params[:y1].to_f,params[:y2].to_f, params[:x1].to_f,params[:x2].to_f])
    else
      @bus_stops = BusStop.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bus_stops }
    end
  end

  # GET /bus_stops/1
  # GET /bus_stops/1.json
  def show
    @bus_stop = BusStop.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bus_stop }
    end
  end

  # GET /bus_stops/new
  # GET /bus_stops/new.json
  def new
    @bus_stop = BusStop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bus_stop }
    end
  end

  # GET /bus_stops/1/edit
  def edit
    @bus_stop = BusStop.get(params[:id])
  end

  # POST /bus_stops
  # POST /bus_stops.json
  def create
    params[:bus_stop][:user_id] = current_user.id
    @bus_stop = BusStop.new(params[:bus_stop])

    respond_to do |format|
      if @bus_stop.save
        format.html { redirect_to @bus_stop, notice: 'Bus stop was successfully created.' }
        format.json { render json: @bus_stop, status: :created, location: @bus_stop }
      else
        format.html { render action: "new" }
        format.json { render json: @bus_stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bus_stops/1
  # PUT /bus_stops/1.json
  def update
    @bus_stop = BusStop.get(params[:id])

    respond_to do |format|
      if @bus_stop.update(params[:bus_stop])
        format.html { redirect_to @bus_stop, notice: 'Bus stop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bus_stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_stops/1
  # DELETE /bus_stops/1.json
  def destroy
    @bus_stop = BusStop.get(params[:id])
    @bus_stop.destroy

    respond_to do |format|
      format.html { redirect_to bus_stops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bus_stops_helper.rb
module BusStopsHelper
end

app/views/bus_stops/_form.html.haml
%script{:type => "text/javascript" , :src => "http://maps.googleapis.com/maps/api/js?key=#{Yetting.maps}&sensor=false"}
= javascript_include_tag 'map_functions'
= javascript_include_tag 'ui.geo_autocomplete'
:javascript
  tMarker = null;
  function loadGeoAutocomplete() {
    map = new google.maps.Map(document.getElementById("demo2_map"), { mapTypeId: google.maps.MapTypeId.ROADMAP, center: new google.maps.LatLng(19.09, 72.91), zoom: 11 });
    showBusStops = false;
    var m;
    google.maps.event.addListener(map, 'click', function(event) {
      $('#bus_stop_lat').val(event.latLng.lat());
      $('#bus_stop_lng').val(event.latLng.lng());
      if (m) {
        m.setPosition(event.latLng); 
      } else {
        m = new google.maps.Marker({map: map, position: event.latLng});
      }
    });
    google.maps.event.addListener(map, 'moveend', function() {
      loadBusStops(map.getBounds());
    });
    google.maps.event.addListener(map, 'dragend', function() {
      loadBusStops(map.getBounds());
    });

    $('#bus_stop_name').geo_autocomplete({
      select: function(_event, _ui) {
        if (_ui.item.viewport) map.fitBounds(_ui.item.viewport);
        $('#bus_stop_lat').attr('value',_ui.item.lat);
        $('#bus_stop_lng').attr('value',_ui.item.lng);
        loadBusStops(map.getBounds());
        if (tMarker) { 
          tMarker.setPosition(new google.maps.LatLng(parseFloat(_ui.item.lat), parseFloat(_ui.item.lng)));
        } else {
          tMarker = getMarker(_ui.item.lat, _ui.item.lng, null, _ui.item.label);
          tMarker.setMap(map);
        }
      }
    });
  }
  $(document).ready(function() { loadGeoAutocomplete(); showBusStops = true})

.row
  .span3
    = form_for(@bus_stop) do |f|
      - if @bus_stop.errors.any?
        #error_explanation
          %h2
            = pluralize(@bus_stop.errors.count, "error")
            prohibited this bus_stop from being saved
    
          %ul
            - @bus_stop.errors.full_messages.each do |msg|
              %li
                = msg
      %label Name
      = f.text_field :name
    
      
    
      %br
      %label Lat
      = f.text_field :lat
      %br
      %label Lng
      = f.text_field :lng
      = f.submit
  .span8
    #demo2_map{:style => "width: 100%; height: 500px;"}
      

app/views/bus_stops/edit.html.erb
<h1>Editing bus_stop</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus_stop %> |
<%= link_to 'Back', bus_stops_path %>

app/views/bus_stops/index.html.erb
<h1>Listing bus_stops</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bus_stops.each do |bus_stop| %>
  <tr>
    <td><%= link_to 'Show', bus_stop %></td>
    <td><%= link_to 'Edit', edit_bus_stop_path(bus_stop) %></td>
    <td><%= link_to 'Destroy', bus_stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bus stop', new_bus_stop_path %>

app/views/bus_stops/new.html.erb
<h1>Add a bus stop</h1>

<%= render 'form' %>

app/views/bus_stops/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_bus_stop_path(@bus_stop) %> |
<%= link_to 'Back', bus_stops_path %>